const DB_FETCH = "DB_FETCH";
const DB_FETCH_FAILED = "DB_FETCH_FAILED";
const DB_FETCH_SUCCESS = "DB_FETCH_SUCCESS";

const FETCH_USER = "FETCH_USER";
const FETCH_USER_FAILED = "FETCH_USER_FAILED";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

const DB_ADD_NEW_ENTRY = "DB_ADD_NEW_ENTRY";
const DB_ADD_NEW_ENTRY_SUCCESS = "DB_ADD_NEW_ENTRY_SUCCESS";
const DB_ADD_NEW_ENTRY_FAILED = "DB_ADD_NEW_ENTRY_FAILED";
const DB_SET_ERROR = "DB_SET_ERROR";

const REGISTER_FORM_ACTION = "REGISTER_FORM_ACTION";
const SET_NAME_REGISTER = "SET_NAME_REGISTER";
const SET_NAME_LOGIN = "SET_NAME_LOGIN";
const SET_EMAIL_REGISTER = "SET_EMAIL_REGISTER";
const SET_PASSWORD_REGISTER = "SET_PASSWORD_REGISTER";
const SET_GENDER_REGISTER = "SET_GENDER_REGISTER";
const SET_BIRTHDAY_REGISTER = "SET_BIRTHDAY_REGISTER";
const SET_BIRTHTIME_REGISTER = "SET_BIRTHTIME_REGISTER";
const SET_WEIGHT_REGISTER = "SET_WEIGHT_REGISTER";

const SET_REGISTER_BUTTON_STATE = "SET_REGISTER_BUTTON_STATE";
const SET_REGISTER_ERROR = "SET_REGISTER_ERROR";
const CLEAN_REGISTER_ERROR = "CLEAN_REGISTER_ERROR";
const CLEAR_MODEL = "CLEAR_MODEL";
const SET_LOADING = "SET_LOADING";

export default {
  DB_FETCH,
  DB_FETCH_FAILED,
  DB_FETCH_SUCCESS,
  FETCH_USER,
  FETCH_USER_FAILED,
  FETCH_USER_SUCCESS,
  DB_ADD_NEW_ENTRY,
  DB_ADD_NEW_ENTRY_FAILED,
  DB_ADD_NEW_ENTRY_SUCCESS,
  DB_SET_ERROR,
  REGISTER_FORM_ACTION,
  SET_NAME_REGISTER,
  SET_NAME_LOGIN,
  SET_EMAIL_REGISTER,
  SET_PASSWORD_REGISTER,
  SET_GENDER_REGISTER,
  SET_BIRTHDAY_REGISTER,
  SET_BIRTHTIME_REGISTER,
  SET_WEIGHT_REGISTER,
  SET_REGISTER_BUTTON_STATE,
  SET_REGISTER_ERROR,
  CLEAN_REGISTER_ERROR,
  CLEAR_MODEL,
  SET_LOADING
}
